### ISSUE TITLE
How to build it for local testing

### ISSUE THREAD

**Issue by EgidioCaprino** [benhowell/react-grid-gallery#105]
Hi all 👋

I've made some changes and I'd like to test them on a local project. I'm trying to build it with `gulp` but it fails.

```
➜  react-grid-gallery git:(master) ✗ node_modules/.bin/gulp
[19:43:23] Using gulpfile ~/Workspace/react-grid-gallery/gulpfile.js
[19:43:23] Starting 'default'...
[19:43:23] Starting 'build-all'...
[19:43:23] Starting 'clean-lib'...
[19:43:23] Finished 'build-all' after 6.15 ms
[19:43:23] Finished 'default' after 6.93 ms
[19:43:23] Finished 'clean-lib' after 22 ms
[19:43:23] Starting 'build-lib'...
[19:43:23] Finished 'build-lib' after 375 ms
[19:43:23] Starting 'build-cljs-lib'...
Error: Cannot find module '/home/egidio/Workspace/react-grid-gallery/src/require.js' from '/home/egidio/Workspace/react-grid-gallery'
    at /home/egidio/Workspace/react-grid-gallery/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/home/egidio/Workspace/react-grid-gallery/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/egidio/Workspace/react-grid-gallery/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/egidio/Workspace/react-grid-gallery/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqCallback.oncomplete (fs.js:160:21) Cannot find module '/home/egidio/Workspace/react-grid-gallery/src/require.js' from '/home/egidio/Workspace/react-grid-gallery'
[19:43:23] Finished 'build-cljs-lib' after 11 ms
[19:43:23] Starting 'clean-web'...
[19:43:23] Finished 'clean-web' after 824 μs
[19:43:23] Starting 'browserify'...
[19:43:23] Starting 'copy-css'...
[19:43:23] Starting 'copy-html'...
[19:43:23] Finished 'copy-html' after 4.63 ms
[19:43:24] Finished 'copy-css' after 305 ms
[19:43:27] Finished 'browserify' after 3.77 s
[19:43:27] Starting 'deploy-web'...
/home/egidio/Workspace/react-grid-gallery/node_modules/gift/lib/commit.js:145
      ref1 = /^.+? (.*) (\d+) .*$/.exec(line), m = ref1[0], actor = ref1[1], epoch = ref1[2];
                                                       ^

TypeError: Cannot read property '0' of null
    at Function.module.exports.Commit.actor (/home/egidio/Workspace/react-grid-gallery/node_modules/gift/lib/commit.js:145:56)
    at Function.module.exports.Commit.parse_commits (/home/egidio/Workspace/react-grid-gallery/node_modules/gift/lib/commit.js:111:21)
    at /home/egidio/Workspace/react-grid-gallery/node_modules/gift/lib/commit.js:55:39
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:978:16)
    at Socket.stream.socket.on (internal/child_process.js:395:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:613:12)
```

What am I missing here?

**Comment by benhowell** [comment]
Hi @EgidioCaprino, as a quick fix, I'd try building without the call to <code>'build-cljs-lib'</code> by commenting out/removing the following line: https://github.com/benhowell/react-grid-gallery/blob/master/gulpfile.js#L29

That task builds a clojurescript library for a side project I had a while back so I should remove it.

Hopefully removing that line will fix things in the mean time as it might be a while before I can get some free time to make a permanent fix.

**Comment by EgidioCaprino** [comment]
Hi @benhowell 

I've commented out line 29 from `gulpfile.js`

``` js
gulp.task('build-all', function() {
    runSequence(
        'clean-lib',
        'build-lib',
        // 'build-cljs-lib',
        'clean-web',
        ['browserify', 'copy-css', 'copy-html'],
        'deploy-web');
});
```

however I still get an error:

``` bash
➜  react-grid-gallery git:(drag-and-drop) ✗ node_modules/.bin/gulp
[18:56:29] Using gulpfile ~/workspace/react-grid-gallery/gulpfile.js
[18:56:29] Starting 'default'...
[18:56:29] Starting 'build-all'...
[18:56:29] Starting 'clean-lib'...
[18:56:29] Finished 'build-all' after 6.71 ms
[18:56:29] Finished 'default' after 8.15 ms
[18:56:29] Finished 'clean-lib' after 36 ms
[18:56:29] Starting 'build-lib'...
[18:56:29] Finished 'build-lib' after 638 ms
[18:56:29] Starting 'clean-web'...
[18:56:29] Finished 'clean-web' after 2.89 ms
[18:56:29] Starting 'browserify'...
[18:56:29] Starting 'copy-css'...
[18:56:29] Starting 'copy-html'...
[18:56:29] Finished 'copy-html' after 10 ms
[18:56:30] Finished 'copy-css' after 526 ms
[18:56:35] Finished 'browserify' after 5.34 s
[18:56:35] Starting 'deploy-web'...
/Users/egidiocaprino/workspace/react-grid-gallery/node_modules/gift/lib/commit.js:145
      ref1 = /^.+? (.*) (\d+) .*$/.exec(line), m = ref1[0], actor = ref1[1], epoch = ref1[2];
                                                       ^

TypeError: Cannot read property '0' of null
    at Function.module.exports.Commit.actor (/Users/egidiocaprino/workspace/react-grid-gallery/node_modules/gift/lib/commit.js:145:56)
    at Function.module.exports.Commit.parse_commits (/Users/egidiocaprino/workspace/react-grid-gallery/node_modules/gift/lib/commit.js:111:21)
    at /Users/egidiocaprino/workspace/react-grid-gallery/node_modules/gift/lib/commit.js:55:39
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

**Comment by benhowell** [comment]
I don't know what gift is but it isn't part of react grid gallery.
